module.exports = {
    "sim": "Sim",
    "nao": "Não",
    "todos": "Todos",
    "todas": "Todas",
    "paciente": "Paciente",
    "hoje": "Hoje",
    "quantidade": "Quantidade",
    "v.data": "Informe uma data",
    "v.descricao": "Informe uma descrição",
    "v.peso": "Informe o peso do paciente",
    "v.altura": "Informe a altura do paciente",
    "v.horario": "Informe um horário",

    "register.v.nome": "Digite seu nome para se registrar",
    "register.v.email": "Digite seu e-mail para se registrar",
    "register.v.emailUtilizado": "Este e-mail já foi utilizado anteriormente.",
    "register.v.repeatEmail": "Repita seu e-mail para se registrar",
    "register.v.emailDiferente": "O email digitado não está igual.",
    "register.v.senha": "Digite uma senha para se registrar",
    "register.v.termosDeUso": "É necessário aceitar os termos de uso.",
    "register.v.telefone": "Digite uma telefone para se registrar",
    "register.v.telefoneInvalido": "Telefone inválido.",

    "antropometria.descricao": "ª Avaliação Física",
    "antropometria.imc": "IMC",
    "antropometria.imcAtual": "IMC",
    "antropometria.tipo.infantil.bebe": "Bebê",
    "antropometria.tipo.infantil.crianca": "Criança",
    "antropometria.tipo.infantil.adolescente": "Adolescente",
    "antropometria.faixaEtaria.ate2": "Crianças de 0 a 1 Ano e 11 Meses",
    "antropometria.faixaEtaria.ate5": "Crianças de até 5 anos",
    "antropometria.faixaEtaria.ate10": "Crianças de até 10 anos",
    "antropometria.faixaEtaria.ate18": "Adolescentes de 10 a 18 anos e 11 Meses",
    "antropometria.pesoParaIdade": "Peso para Idade",
    "antropometria.pesoParaEstatura": "Peso para Estatura",
    "antropometria.estaturaParaIdade": "Estatura para Idade",
    "antropometria.previsaoDeParto": "Previsão do parto",
    "antropometria.imcPreGestacional": "IMC Pré-Gestacional",
    "antropometria.ganhoDePeso": "Ganho de peso",    
    "antropometria.recomendacaoGanhoDePesoTotal": "Ganho de peso ao final da gravidez",
    "antropometria.riscoCardiovascular": "Risco cardiovascular",
    "antropometria.razaoCinturaQuadril": "Razão cintura / quadril",
    "antropometria.massaGorda": "Massa Gorda",
    "antropometria.massaMagra": "Massa Magra",
    "antropometria.percMassaGorda": "% Massa Gorda",
    "antropometria.percMassaMagra": "% Massa Magra",
    "antropometria.densidade": "Densidade Corporal",
    "antropometria.pesoOsseo": "Peso Ósseo",
    "antropometria.pesoResidual": "Peso Residual",
    "antropometria.pesoMuscular": "Peso Muscular",
    "antropometria.protocolo2": "3 Pregas: Guedes (Características Brasileiras)",
    "antropometria.protocolo3": "3 Pregas: Jackson & Pollock",
    "antropometria.protocolo4": "4 Pregas: Durnin & Womersley",
    "antropometria.protocolo5": "4 Pregas: Faulkner",
    "antropometria.protocolo6": "4 Pregas: Petroski (Características Brasileiras)",
    "antropometria.protocolo7": "7 Pregas: Jackson, Pollock & Ward",
    "antropometria.grafico.pesoAltura": "Peso x Altura (OMS)",
    "antropometria.grafico.pesoIdade": "Peso x Idade (meses) (OMS)",
    "antropometria.grafico.alturaIdade": "Altura x Idade (meses) (OMS)",
    "antropometria.grafico.imcIdade": "IMC x Idade (meses) (OMS)",
    "antropometria.percentil03": "Percentil 3",
    "antropometria.percentil15": "Percentil 15",
    "antropometria.percentil50": "Percentil 50",
    "antropometria.percentil85": "Percentil 85",
    "antropometria.percentil97": "Percentil 97",
    "antropometria.confirm.carregarUltima": "Ao carregar os dados da ultima antropometria, os dados não salvos serão perdidos. Carregar os dados da última antropometria?",
    "antropometria.confirm.enviarPorEmail": "Enviar esta antropometria por e-mail para o(a) <strong>{0}</strong>?",
    "antropometria.notificacao.comparativoEnviado": "Comparativo Antropométrico enviado para ",
    "antropometria.v.pesoPreGestacional": "Informe o peso pré-gestacional",
    "antropometria.v.idadeGestacional": "Informe a idade gestacional",

    "anamnese.notificacao.sucesso": "Anamnese salva com sucesso.",
    "anamnese.notificacao.removida": "Anamnese removida com sucesso.",
    "anamnese.confirm.carregarUltima": "Ao carregar os dados da última anamnese, você perderá qualquer dado preenchido ainda não salvo. Carregar a última anamnese?",
    "anamnese.confirm.enviarPorEmail": "Enviar esta anamnese por e-mail para o(a) <strong>{0}</strong>?",
    "anamnese.v.informeocasoclinico": "Informe o caso clínico",


    "plano.descricao": "Plano alimentar para ",
    "plano.referencia.null": "Não configurado",
    "plano.referencia.energia": "Energia: ",
    "plano.referencia.proteina": "Proteína: ",
    "plano.referencia.cho": "CHO: ",
    "plano.referencia.lipideos": "Lipídeos: ",
    "plano.referencia.peso": "Peso: ",
    "plano.meusAlimentos": "Meus Alimentos",
    "plano.refeicao.desjejum": "Desjejum",
    "plano.refeicao.cafeDaManha": "Café da manhã",
    "plano.refeicao.colacao": "Colação",
    "plano.refeicao.almoco": "Almoço",
    "plano.refeicao.lancheDaTarde": "Lanche da tarde",
    "plano.refeicao.pretreino": "Pré-treino",
    "plano.refeicao.postreino": "Pós-treino",
    "plano.refeicao.jantar": "Jantar",
    "plano.refeicao.ceia": "Ceia",
    "plano.valorCalorico": "Valor Calórico",
    "plano.semProteinaKilo": "Informe o peso do paciente nos valores de referência",
    "plano.macronutrientes.proteinas": "Proteínas",
    "plano.macronutrientes.carboidratos": "Carboidratos",
    "plano.macronutrientes.gordurasTotais": "Gorduras totais",
    "plano.micronutrientes.fibraAlimentar": "Fibra alimentar",
    "plano.micronutrientes.calcio": "Cálcio",
    "plano.micronutrientes.sodio": "Sódio",
    "plano.micronutrientes.selenio": "Selênio",
    "plano.micronutrientes.vitaminaA": "Vitamina A (Retinol)",
    "plano.micronutrientes.vitaminaC": "Vitamina C (Ácido ascórbico)",
    "plano.micronutrientes.vitaminaD": "Vitamina D (Calciferol)",
    "plano.micronutrientes.vitaminaE": "Vitamina E (Tocoferol)",
    "plano.micronutrientes.vitaminaB1": "Vitamina B1 (Tiamina)",
    "plano.micronutrientes.vitaminaB2": "Vitamina B2 (Riboflavina)",
    "plano.micronutrientes.vitaminaB3": "Vitamina B3 (Niacina)",
    "plano.micronutrientes.vitaminaB6": "Vitamina B6 (Piridoxina)",
    "plano.micronutrientes.vitaminaB9": "Vitamina B9 (Ácido fólico)",
    "plano.micronutrientes.vitaminaB12": "Vitamina B12 (Cobalamina)",
    "plano.micronutrientes.ferro": "Ferro",
    "plano.micronutrientes.fosforo": "Fósforo (P)",
    "plano.micronutrientes.potassio": "Potássio",
    "plano.micronutrientes.Zinco": "Zinco",
    "plano.micronutrientes.magnesio": "Magnésio",
    "plano.micronutrientes.manganes": "Manganês",
    "plano.micronutrientes.acucarTotal": "Açucar Total",
    "plano.micronutrientes.gTrans": "G. Trans",
    "plano.micronutrientes.colesterol": "Colesterol",
    "plano.micronutrientes.gSaturada": "G. Saturada",
    "plano.micronutrientes.gPoliInsaturada": "G. Poli-insaturada",
    "plano.micronutrientes.gMonoinsaturada": "G. Monoinsaturada",
    "plano.dias.nenhum": "Nenhum dia (Inativo)",
    "plano.dias.todos": "Todos os dias",
    "plano.dias.seg_a_sex": "Seg à Sex",
    "plano.dias.fimDeSemana": "Fim de semana",
    "plano.dias.seg": "Seg",
    "plano.dias.ter": "Ter",
    "plano.dias.qua": "Qua",
    "plano.dias.qui": "Qui",
    "plano.dias.sex": "Sex",
    "plano.dias.sab": "Sáb",
    "plano.dias.dom": "Dom",
    "plano.notificacao.sucesso": "Plano Alimentar salvo com sucesso.",
    "plano.notificacao.semGastosEnergeticos": "Este paciente não possui gastos energéticos cadastrados.",
    "plano.notificacao.grupoRemovido": "Grupo removido com sucesso.",
    "plano.notificacao.grupoEmUso": "Não é possivel remover grupo em uso.",
    "plano.confirm.alterarTipo": "Alterar o tipo da dieta?<br />Isto removerá as refeições existentes.",
    "plano.confirm.carregarReferenias": "Carregar os últimos gastos energéticos como referência? Isto irá mudar o valor atual deste campo.",
    "plano.confirm.carregarPlano": "Substituir o plano alimentar atual pelo {0}?",
    "plano.confirm.adicionarRefeicao": "Parece que você está querendo adicionar uma nova refeição. Salvar a refeição atual e incluir uma nova?",
    "plano.confirm.removerRefeicao": "Remover esta refeição?",
    "plano.confirm.removerGrupo": "Remover o grupo de alimento {0}?",
    "plano.confirm.substituirTitle": "Substituir",
    "plano.confirm.substituirContent": "Existem outros planos alimentares ativos para esses dias. Salvar os antigos como histórico e substituir o ativo?",
    "plano.confirm.delete": "Esta operação não poderá ser desfeita.<br />Remover {0}?",
    "plano.v.alimentos": "Informe ao menos um alimento",

    "recordatorio.descricao": "Recordatório para ",
    "recordatorio.notificacao.sucesso": "Recordatório salvo com sucesso.",

    "cardapio.descricao": "Cardápio",
    "cardapio.notificacao.sucesso": "Cardápio salvo com sucesso.",

    "payment.pago": "Pago",
    "payment.pendente": "Pendente",
    "payment.cancelada": "Cancelada",

    "situacao.Baixo": "Baixo",
    "situacao.Sobrepeso": "Sobrepeso",
    "situacao.ObesidadeLeve": "Obesidade grau I",
    "situacao.ObesidadeModerada": "Obesidade grau II",
    "situacao.ObesidadeSevera": "Obesidade grau III",
    "situacao.AbaixoDaMedia": "Abaixo da média",
    "situacao.PiorQueMedia": "Pior que a média",
    "situacao.Ruim": "Ruim",
    "situacao.MuitoRuim": "Muito ruim",
    "situacao.Excesso": "Excesso",
    "situacao.Excelente": "Excelente",
    "situacao.Bom": "Bom",
    "situacao.AcimaDaMedia": "Acima da média",
    "situacao.MelhorQueMedia": "Melhor que a média",
    "situacao.Media": "Média",
    "situacao.Ideal": "Ideal",
    "situacao.Eutrofia": "Eutrofia",
    "situacao.RiscoAlto": "Risco Alto",
    "situacao.RiscoMuitoAlto": "Risco Muito Alto",
    "situacao.RiscoBaixo": "Risco Baixo",
    "situacao.Acima": "Acima",
    "situacao.Abaixo": "Abaixo",
    "situacao.Normal": "Normal",
    "situacao.Obesidade": "Obesidade",
    "situacao.Adequado": "Adequado",
    "situacao.Obstipacao": "Obstipação",
    "situacao.TendenciaDiarreia": "Tendência Diarreia",

    "confirm.title": "Confirmação",
    "confirm.atencao": "Atenção",
    "confirm.remover": "Esta operação não poderá ser desfeita. Remover?",
    "confirm.anexo.remover": "Esta operação não poderá ser desfeita. Remover o arquivo?",
    "confirm.operacaoNaoPodeDesfeitaCerteza": "Esta operação não poderá ser desfeita. Remover {0}?",
    "notificao.salvar.erro": "Falha ao salvar.",
    "notificao.antropometria.sucesso": "Antropometria salva com sucesso.",
    "notificao.remover.sucesso": "Arquivo removido com sucesso.",
    "notificao.remover.erro": "Ops! Não foi possível excluir o arquivo. Tente novamente.",
    "notificao.arquivo.erro": "Ops! Não foi possível processar esta operação. Se você estiver anexando um arquivo, é provavel que este arquivo seja muito grande.",
    "notificao.abrir.erro": "Ops! Não foi possível abrir esse item.",
    "notificao.email.sucesso": "Email enviado com sucesso.",
    "notificao.email.erro": "Ops! Não foi possível enviar o e-mail agora, tente novamente mais tarde."
}